apiVersion: v1
kind: ConfigMap
metadata:
  name: outbib-config
  namespace: outbib
data:
  NODE_ENV: "development"
  REDIS_URL: "redis://redis:6379"
  NATS_URL: "nats://nats:4222"
  MAPS_DEFAULT_COUNTRY: ""
  SYNC_CONCURRENCY: "3"
  APP_URL: "http://outbib.local"
  APP_NAME: "Outbib-PocketDoc"
  AI_MODEL_PRIMARY: "arcee-ai/trinity-large-preview:free"
  AI_MODEL_FALLBACKS: "upstage/solar-pro-3:free,liquid/lfm-2.5-1.2b-instruct:free,allenai/molmo-2-8b:free"
