apiVersion: v1
kind: Secret
metadata:
  name: outbib-secrets
  namespace: outbib
type: Opaque
stringData:
  JWT_SECRET: "change-me"
  JWT_REFRESH_SECRET: "change-me-refresh"
  JWT_REFRESH_EXPIRES_IN: "7d"
  AUTH_ADMIN_EMAIL: "admin@outbib.local"
  AUTH_ADMIN_PASSWORD: "ChangeMe123!@#"
  AUTH_ADMIN_PROMOTE_EXISTING: "false"
  AUTH_ADMIN_BOOTSTRAP_ENABLED: "true"
